@Zadanie4_HostAddress = http://localhost:5128


POST http://localhost:5128/api/warehouse
Content-Type: application/json

{
  "idProduct": 1,
  "idWarehouse": 1,
  "amount": 125,
  "createdAt": "2024-05-08T14:19:33.107Z"
}

###

POST http://localhost:5128/api/warehouse/procedure
Content-Type: application/json

{
  "idProduct": 1,
  "idWarehouse": 1,
  "amount": 125,
  "createdAt": "2024-05-10T14:19:34.107Z"
}